### ISSUE TITLE
App version missing

### ISSUE THREAD

**Issue by yahu1031** [FlutterMatic/desktop#44]
**Describe the bug**
App version is missing in About dialog.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download v0.0.1-alpha version from releases.
2. Extract the files and run `fluttermatic.exe`.
3. Click on info button. and check the version.

**Expected behaviour**
Must give the app version `v0.0.1-alpha`.

**Screenshots**
![image](https://user-images.githubusercontent.com/35523357/150646530-135fcb2d-74f3-4cd6-9f64-ca14a67c700b.png)

**Desktop (please complete the following information):**
 - OS: Windows, macOS

**Comment by ZiyadF296** [comment]
I have a suggested solution for this. I will try it out later and inform if it works or not. I think it's something related with the build command.
