### ISSUE TITLE
[🐛] - Report freezes the whole app in macOS

### ISSUE THREAD

**Issue by yahu1031** [FlutterMatic/desktop#48]
**Describe the bug**
When I try to make a report, Then it freezes the whole app.

**To Reproduce**
1. Go to about dialog.
2. Check out to report section.
3. Click on the report button.
4. Choose the directory to save the logs file to be generated.
5. Then the loading widgets appear and the app was frozen.

**Expected behavior**
Should generate a report and open the GitHub issues page.

**Screen
<img width="1440" alt="Screenshot 2022-01-26 at 5 51 37 PM" src="https://user-images.githubusercontent.com/35523357/151163282-77b0b2e6-98ec-4392-bedf-87b8468c7434.png">
shots**

**Desktop:**
 - OS: macOS

**Logs (please upload the logs file by following the instructions):**
[fm-macos-debug-2022-01-26.log](https://github.com/FlutterMatic/desktop/files/7941688/fm-macos-debug-2022-01-26.log) - Generated by the app default.

**Comment by yahu1031** [comment]
It is related to [path_provider](https://pub.dev/packages/path_provider) package. Path provider package won't work on isolates. This issue was logged here [Flutter-51685](https://github.com/flutter/flutter/issues/51685)

**Comment by yahu1031** [comment]
I was suspecting `_generatePort.asBroadcastStream` this stream.

**Comment by ZiyadF296** [comment]
No, this error is common and can be resolved. Please reference the code that errors out.

**Comment by yahu1031** [comment]
Now, this is fixed. That comment was made while investigating the ticket.

**Comment by ZiyadF296** [comment]
Is this now resolved on macos?

**Comment by ZiyadF296** [comment]
Because your code still contains a mistake

**Comment by ZiyadF296** [comment]
A platform channel related mistake to be concise.

**Comment by yahu1031** [comment]
it works fine in macOS. Please reopen this issue if it still persists with a valid recording/screenshot of the Freezed app.

**Comment by ZiyadF296** [comment]
Reopening until confirmed resolved on all platforms

**Comment by yahu1031** [comment]
Please do share the issue. Cause it is working. Generating logs file works and please fix the logs ASAP.

**Comment by yahu1031** [comment]
This is what the report was generating right now
```log
Report generated on 2022-01-27 00:05:26.372561

---- LOG ---- 
/Users/minnu/Documents/fm_report_2022-1-27-0-5-21
---- LOG ----

Report generated on 2022-01-27 00:05:26.372561
```

**Comment by yahu1031** [comment]
@ZiyadF296 Any update, please...

**Comment by yahu1031** [comment]
I'm opening this because no report was being generated.

**Comment by yahu1031** [comment]
[FlutterMatic\logs\fm-macos-debug-2022-02-02.log](https://github.com/FlutterMatic/desktop/files/7981500/FlutterMatic.logs.fm-macos-debug-2022-02-02.log)
Here are the logs

**Comment by yahu1031** [comment]
Will be created as new issue.
