### ISSUE TITLE
[✨] Ability to automatically add fmatic workflows to `.gitignore`

### ISSUE THREAD

**Issue by ZiyadF296** [FlutterMatic/desktop#56]
### Discussed in https://github.com/FlutterMatic/desktop/discussions/55

<div type='discussions-op-text'>

<sup>Originally posted by **ZiyadF296** January 27, 2022</sup>
**Is your feature request related to a problem? Please describe.**
It is annoying having to manually add `fmatic` folder to `.gitignore` for each individual project

**Describe the solution you'd like**
Option to add folder to project `.gitignore`

**Describe alternatives you've considered**
To do it manually.</div>

**Comment by yahu1031** [comment]
A detailed information required please🙏

**Comment by ZiyadF296** [comment]
Please checkout the workflow feature and you will understand.

**Comment by ZiyadF296** [comment]
Feature has been implemented.
