### ISSUE TITLE
[🐛] Markdown doesn't render correctly in pub docs

### ISSUE THREAD

**Issue by yahu1031** [FlutterMatic/desktop#68]
**Describe the bug**
Markdown on pub docs wasn't rendering correctly
EG: `>` and `code blocks`.
```
`
```
This back quote is being converted to `>`.
<img width="1251" alt="Screenshot 2022-02-18 at 12 08 08 AM" src="https://user-images.githubusercontent.com/35523357/154548444-e924170c-5761-4e4e-8877-3c6ee79f93e5.png">

Missing some tags (EG: Discord)

This tag gives 
```
════════ Exception caught by SVG ═══════════════════════════════════════════════
The following UnsupportedError was thrown in _Element.svg:
Unsupported operation: Unsupported nested <svg> element.

The root <svg> element contained an unsupported nested SVG element.

Picture key: NetworkPicture("[https://codecov.io/gh/rrousselGit/provider/branch/master/graph/badge.svg]()", headers: null, colorFilter: null)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by SVG ═══════════════════════════════════════════════
Exception: Invalid image data
════════════════════════════════════════════════════════════════════════════════
```
Error
**To Reproduce**
1. Go to the Pub tab
2. Click on provider package

**Expected behavior**
It must show the discord tag. Not only discord and some other packages tags were being missed.

**Screenshots**
<img width="542" alt="Screenshot 2022-02-18 at 12 05 23 AM" src="https://user-images.githubusercontent.com/35523357/154548042-4b65986e-1ff1-49a5-804b-3b2eba7d189a.png">

**Desktop (please complete the following information):**
 - OS: macOS

**Logs (please upload the logs file by following the instructions):**
Unable to generate logs

**Comment by ZiyadF296** [comment]
This issue is aware of and already noted earlier. It is related to the changelog rendering issue. If that gets solved this gets solved too (same markdown rendering widget)

**Comment by ZiyadF296** [comment]
#50

**Comment by yahu1031** [comment]
But this doesn't come under pub API.

**Comment by yahu1031** [comment]
Make it backlogged. Don't close it.

**Comment by yahu1031** [comment]
That is why I backlogged and triaged it.

**Comment by ZiyadF296** [comment]
It has already been removed. Push is pending.

**Comment by ZiyadF296** [comment]
Please review and close. Thanks 😊

**Comment by yahu1031** [comment]
Checked and verified.
