### ISSUE TITLE
[🐛] Cannot fetch pub packages in macOS

### ISSUE THREAD

**Issue by yahu1031** [FlutterMatic/desktop#69]
**Describe the bug**
When I try to search a package EG: `at_contacts`. It shows an error message.

**To Reproduce**
1. Go to the pub tab
2. Search for a package

**Expected behavior**
It must show the resulting packages list.

**Screenshots**
<img width="533" alt="Screenshot 2022-02-18 at 12 10 36 AM" src="https://user-images.githubusercontent.com/35523357/154549072-a10b8a09-cbe9-45d1-b1e5-1beac5424ff8.png">

**Desktop (please complete the following information):**
 - OS: macOS

**Logs (please upload the logs file by following the instructions):**
 Unable to generate logs.

**Comment by ZiyadF296** [comment]
This is not an issue. The search feature is in pre-release. Nothing should work properly in it.

**Comment by yahu1031** [comment]
This issue was raised as of the feature available.

**Comment by ZiyadF296** [comment]
> This issue was raised as of the feature available. 

Well, the feature is partially available. As stated in the pre-release tag.

**Comment by ZiyadF296** [comment]
Will keep this open until the search for pub packages becomes stable.

**Comment by ZiyadF296** [comment]
This issue has been fixed with the latest push. Please pull the changes and check to see if it works as expected.

**Comment by yahu1031** [comment]
I will update this sometime later

**Comment by ZiyadF296** [comment]
If you are experiencing this issue still, please file it in a new issue.

**Comment by yahu1031** [comment]
Please close this with a valid fix

**Comment by yahu1031** [comment]
FYI this is for MacOS not for any other platforms. So please keep this opened until this is fixed

**Comment by ZiyadF296** [comment]
If you are experiencing this issue still, please file it in a new issue.

Keep this in mind. THIS is now CLOSED. Reference it in a new issue if it persists.

**Comment by yahu1031** [comment]
But why new ticket? when we already have one here

**Comment by ZiyadF296** [comment]
Last time, this issue has been fully resolved in a recent commit. Please DO NOT reopen this issue one more time. If you have anything that doesn't work, create a separate issue for it. Once an issue IS CLOSED, it REMAINS CLOSED.

**Comment by yahu1031** [comment]
> Once an issue IS CLOSED, it REMAINS CLOSED

@ZiyadF296 Any specific reason?

**Comment by ZiyadF296** [comment]
Consistency. It's not about whether or not the author likes the fix. And it's not up to the author if the fix works or not. The person who created the fix has tested it on their own machine. If you test on your own machine and it doesn't work then that is a separate issue that is specific to your machine, which should be filed in a new issue to fix that system specific issue.

**Comment by yahu1031** [comment]
> the author likes the fix. 

FYI Please watch them.

I never said I like it or dislike it. Moreover, this issue/ticket was raised with a platform-specific. 
The ticket handler(@ZiyadF296) has removed the platform-specific tag and asking to duplicate the issue now?

> The person who created the fix has tested it on their own machine.

Can you please provide what machine it is and a screenshot of it so that I(the ticket author) can make sure of confirming the fix?

Again FYI duplication of tickets is a bad practice of managing a project as a team. So would like to reopen it again with the above reason mentioned. Hoping you will provide a macOS fix but not a Windows/Linux fix.

**Comment by ZiyadF296** [comment]
This has been fixed. Please check the LATEST COMMIT.

**Comment by ZiyadF296** [comment]
I didn't have to mention that this ISSUE IS FIXED. IT IS NOT PLATFORM-SPECIFIC. STOP REOPENING ISSUES. You aren't even contributing to this project to be bossing and managing around here.

**Comment by yahu1031** [comment]
I used to. Still, I can but there are quite some complications to contribute to this. And moreover, respect the customers.

**Comment by yahu1031** [comment]
<img width="1440" alt="Screenshot 2022-02-25 at 1 16 02 AM" src="https://user-images.githubusercontent.com/35523357/155596294-6bb0e2f4-4e25-41e1-870b-feca79c596fd.png">

```logs
Launching lib[/main.dart]() on macOS in debug mode...
lib/main.dart:1
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:99C53EBE-5E59-52B9-A911-CAB3325DD8FC }
{ platform:macOS, name:Any Mac }
Connecting to VM Service at ws://127.0.0.1:59079[/ZgWzw9U6t_Y]()=[/ws]()
flutter: 📂 AppData path: [/Users/minnu/Library/Application]() Support[/FlutterMatic]()
[log] INFORMATION [01:11:13] - Dark theme setter set to true.
[log] INFORMATION [01:11:14] - : 208.67 GB out of 229.37 GB left
[log] INFORMATION [01:11:14] - : 0.47 GB out of 0.48 GB left
[log] WARNING [01:11:14] - Disk  has only 0.47 left.
[log] INFORMATION [01:11:14] - : 0.47 GB out of 0.47 GB left
[log] WARNING [01:11:14] - Disk  has only 0.47 left.
[log] INFORMATION [01:11:14] - : 208.67 GB out of 209.12 GB left
[log] INFORMATION [01:11:14] - : 208.67 GB out of 208.68 GB left
[log] INFORMATION [01:11:14] - : 0.47 GB out of 0.48 GB left
[log] WARNING [01:11:14] - Disk  has only 0.47 left.
[log] INFORMATION [01:11:14] - : 208.67 GB out of 432.38 GB left
[log] INFORMATION [01:11:14] - : 208.67 GB out of 214.67 GB left
[log] INFORMATION [01:11:14] - DEVFS: 0.00 GB out of 0.00 GB left
[log] WARNING [01:11:14] - Disk DEVFS has only 0.00 left.
[log] INFORMATION [01:11:14] - : 208.67 GB out of 229.37 GB left
[log] ERROR [01:11:14] - Drive conflicting error found. Drives: [/dev/disk3s1](), [/dev/disk1s1](), [/dev/disk1s3](), [/dev/d...]()
[log] INFORMATION [01:11:14] - Disk space check passed. Disk is writable.
[log] WARNING [01:11:14] - Lost connection. FlutterMatic is offline.
[log] INFORMATION [01:11:15] - Back online. FlutterMatic is online.
[log] INFORMATION [01:11:15] - Dart version: 2.16.1
[log] INFORMATION [01:11:15] - Dart channel: stable
[log] INFORMATION [01:11:16] - VSCode found on system: 1.64.2
[log] INFORMATION [01:11:16] - ADB found on system: 1.0.41
[log] INFORMATION [01:11:17] - Flutter found on system: 2.10.2
[log] INFORMATION [01:11:17] - Java found on system: 1.8.0-321
[log] INFORMATION [01:11:17] - Git found on system: 2.32.0
[log] INFORMATION [01:11:21] - No new FlutterMatic version found. Current version: v0.0.1-alpha
```

Like 4 mins

**Comment by ZiyadF296** [comment]
I haven't crossed the line of respect, my friend. As a matter of fact, I have been trying to explain all along that this issue is solved, and you fail to notice that. I think that we can just leave this issue closed because:
- It wasn't a bug
- It isn't platform-specific
- It is a feature request (and it is implemented)

I think that you didn't look over the issue very well, instead, you just are logging issue after issue, without uploading the log files saved on your system, associating the wrong tags, always adding the `macOS` tag, before confirming in any way that it is only on `macOS` and not also on `windows` or `linux`. You don't tag them as `triage` at first to get opinions and ideas and a proven log that shows the issue taking place. This is not well coordinated and needs to change.

Having to deal with fixing all issues as soon as they are created so that I can make each individual using this app satisfied with minimal complications with errors is surely no easy task. Additionally, you are adding the burden of dealing with all of this rather than following the extremely simple set of instructions for how issuing on this repo should work and is supposed to work.

If you can't keep up with these simple instructions, then simply you don't have to file these issues or be related to this app in any way, it's isn't a requirement, and nobody is forcing you to do any of this. This is a free contribution you are providing, and you are crossing the line in some zones.

I am sure anyone using this app appreciates each and every single contributor, but come on, we must have a fun little zone of ours where we respect one another and keep this open-source community toxic-free. It's a sheer will, but worthy.

Think about it, lets follow a consistent ticketing scheme that I suggested and have been using since the beginning. That is all I am asking for, only that.

In any case, I do appreciate you filling and catching sneaky glitches and bugs across the app, I really do.

**Comment by ZiyadF296** [comment]
> <img alt="Screenshot 2022-02-25 at 1 16 02 AM" width="1440" src="https://user-images.githubusercontent.com/35523357/155596294-6bb0e2f4-4e25-41e1-870b-feca79c596fd.png">
> 
> ```
> Launching lib[/main.dart]() on macOS in debug mode...
> lib/main.dart:1
> --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> { platform:macOS, arch:x86_64, id:99C53EBE-5E59-52B9-A911-CAB3325DD8FC }
> { platform:macOS, name:Any Mac }
> Connecting to VM Service at ws://127.0.0.1:59079[/ZgWzw9U6t_Y]()=[/ws]()
> flutter: 📂 AppData path: [/Users/minnu/Library/Application]() Support[/FlutterMatic]()
> [log] INFORMATION [01:11:13] - Dark theme setter set to true.
> [log] INFORMATION [01:11:14] - : 208.67 GB out of 229.37 GB left
> [log] INFORMATION [01:11:14] - : 0.47 GB out of 0.48 GB left
> [log] WARNING [01:11:14] - Disk  has only 0.47 left.
> [log] INFORMATION [01:11:14] - : 0.47 GB out of 0.47 GB left
> [log] WARNING [01:11:14] - Disk  has only 0.47 left.
> [log] INFORMATION [01:11:14] - : 208.67 GB out of 209.12 GB left
> [log] INFORMATION [01:11:14] - : 208.67 GB out of 208.68 GB left
> [log] INFORMATION [01:11:14] - : 0.47 GB out of 0.48 GB left
> [log] WARNING [01:11:14] - Disk  has only 0.47 left.
> [log] INFORMATION [01:11:14] - : 208.67 GB out of 432.38 GB left
> [log] INFORMATION [01:11:14] - : 208.67 GB out of 214.67 GB left
> [log] INFORMATION [01:11:14] - DEVFS: 0.00 GB out of 0.00 GB left
> [log] WARNING [01:11:14] - Disk DEVFS has only 0.00 left.
> [log] INFORMATION [01:11:14] - : 208.67 GB out of 229.37 GB left
> [log] ERROR [01:11:14] - Drive conflicting error found. Drives: [/dev/disk3s1](), [/dev/disk1s1](), [/dev/disk1s3](), [/dev/d...]()
> [log] INFORMATION [01:11:14] - Disk space check passed. Disk is writable.
> [log] WARNING [01:11:14] - Lost connection. FlutterMatic is offline.
> [log] INFORMATION [01:11:15] - Back online. FlutterMatic is online.
> [log] INFORMATION [01:11:15] - Dart version: 2.16.1
> [log] INFORMATION [01:11:15] - Dart channel: stable
> [log] INFORMATION [01:11:16] - VSCode found on system: 1.64.2
> [log] INFORMATION [01:11:16] - ADB found on system: 1.0.41
> [log] INFORMATION [01:11:17] - Flutter found on system: 2.10.2
> [log] INFORMATION [01:11:17] - Java found on system: 1.8.0-321
> [log] INFORMATION [01:11:17] - Git found on system: 2.32.0
> [log] INFORMATION [01:11:21] - No new FlutterMatic version found. Current version: v0.0.1-alpha
> ```
> 
> Like 5 mins @ZiyadF296

This is a different issue :) please create a new issue for it. It's not related to this one ✌️

**Comment by yahu1031** [comment]
okie please tell me what this issue should be named

**Comment by ZiyadF296** [comment]
It's your issue, whatever is suitble should be named.

**Comment by yahu1031** [comment]
this suits and this is the issue getting continued :(

**Comment by ZiyadF296** [comment]
Did you take your time to read this message?

> I haven't crossed the line of respect, my friend. As a matter of fact, I have been trying to explain all along that this issue is solved, and you fail to notice that. I think that we can just leave this issue closed because:
> 
> * It wasn't a bug
> * It isn't platform-specific
> * It is a feature request (and it is implemented)
> 
> I think that you didn't look over the issue very well, instead, you just are logging issue after issue, without uploading the log files saved on your system, associating the wrong tags, always adding the `macOS` tag, before confirming in any way that it is only on `macOS` and not also on `windows` or `linux`. You don't tag them as `triage` at first to get opinions and ideas and a proven log that shows the issue taking place. This is not well coordinated and needs to change.
> 
> Having to deal with fixing all issues as soon as they are created so that I can make each individual using this app satisfied with minimal complications with errors is surely no easy task. Additionally, you are adding the burden of dealing with all of this rather than following the extremely simple set of instructions for how issuing on this repo should work and is supposed to work.
> 
> If you can't keep up with these simple instructions, then simply you don't have to file these issues or be related to this app in any way, it's isn't a requirement, and nobody is forcing you to do any of this. This is a free contribution you are providing, and you are crossing the line in some zones.
> 
> I am sure anyone using this app appreciates each and every single contributor, but come on, we must have a fun little zone of ours where we respect one another and keep this open-source community toxic-free. It's a sheer will, but worthy.
> 
> Think about it, lets follow a consistent ticketing scheme that I suggested and have been using since the beginning. That is all I am asking for, only that.
> 
> In any case, I do appreciate you filling and catching sneaky glitches and bugs across the app, I really do.

**Comment by yahu1031** [comment]
> I haven't crossed the line of respect, my friend. As a matter of fact, I have been trying to explain all along that this issue is solved, and you fail to notice that. I think that we can just leave this issue closed because:
> 
> * It wasn't a bug
> * It isn't platform-specific
> * It is a feature request (and it is implemented)
> 
> I think that you didn't look over the issue very well, instead, you just are logging issue after issue, without uploading the log files saved on your system, associating the wrong tags, always adding the `macOS` tag, before confirming in any way that it is only on `macOS` and not also on `windows` or `linux`. You don't tag them as `triage` at first to get opinions and ideas and a proven log that shows the issue taking place. This is not well coordinated and needs to change.
> 
> Having to deal with fixing all issues as soon as they are created so that I can make each individual using this app satisfied with minimal complications with errors is surely no easy task. Additionally, you are adding the burden of dealing with all of this rather than following the extremely simple set of instructions for how issuing on this repo should work and is supposed to work.
> 
> If you can't keep up with these simple instructions, then simply you don't have to file these issues or be related to this app in any way, it's isn't a requirement, and nobody is forcing you to do any of this. This is a free contribution you are providing, and you are crossing the line in some zones.
> 
> I am sure anyone using this app appreciates each and every single contributor, but come on, we must have a fun little zone of ours where we respect one another and keep this open-source community toxic-free. It's a sheer will, but worthy.
> 
> Think about it, lets follow a consistent ticketing scheme that I suggested and have been using since the beginning. That is all I am asking for, only that.
> 
> In any case, I do appreciate you filling and catching sneaky glitches and bugs across the app, I really do.

we can talk about this private thing somewhere else but it isn't about toxicity. You aren't providing a valid reason to file a new issue.

**Comment by yahu1031** [comment]
Moreover, I can't find the logs where I choose. and not in the application support dir. It is empty BTW

**Comment by ZiyadF296** [comment]
> this suits and this is the issue getting continued :(

I am the one who wrote the code, I know what is what. This code is not related at all to the code of the search. It is completely two different things. This issue is a feature. And the 5 minute loading error is a bug. Please just follow simple instructions and create a new issue, please. For our sake. Please. I don't have to beg for you to listen for once. lets make this simple and straightforward. Enough of this stupid discussions about stupid and worthless topics.

**Comment by ZiyadF296** [comment]
> Moreover, I can't find the logs where I choose. and not in the application support dir. It is empty BTW

Really? Hmm... file a new issue for that too.

**Comment by yahu1031** [comment]
What the duck is this? How many times i should file a ticket of the same?

**Comment by ZiyadF296** [comment]
These are all different issues you are mentioning.
